version: '3.9'


services:
  db:
    image: postgres:14.3-alpine3.15
    container_name: postgres_pyweb-6hw-flask
    ports:
      - "5430:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}


networks:
  dev_network: